# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 45) do

  create_table "ads", :force => true do |t|
    t.column "adtext", :string
    t.column "status", :integer, :default => 0
  end

  create_table "adsbkp", :force => true do |t|
    t.column "adtext",         :string
    t.column "downloadeddate", :date
  end

  create_table "auxreasons", :force => true do |t|
    t.column "auxcode", :integer
    t.column "reasons", :string
  end

  create_table "auxreasonsbkp", :force => true do |t|
    t.column "auxcode",        :integer
    t.column "reasons",        :string
    t.column "downloadeddate", :date
  end

  create_table "carddetails", :force => true do |t|
    t.column "bin",        :string
    t.column "product",    :string
    t.column "expiredate", :date
    t.column "priority",   :string
  end

  create_table "carddetailsbkp", :force => true do |t|
    t.column "bin",            :string
    t.column "product",        :string
    t.column "expiredate",     :date
    t.column "priority",       :string
    t.column "downloadeddate", :date
  end

  create_table "counters", :force => true do |t|
    t.column "counterno",     :integer
    t.column "loginstatus",   :string,  :limit => 1, :default => "N"
    t.column "counterstatus", :string,  :limit => 1
  end

  create_table "csmappings", :force => true do |t|
    t.column "counterno", :integer
    t.column "serviceid", :string
  end

  create_table "ctypemappings", :force => true do |t|
    t.column "counterno", :integer
    t.column "ctypeid",   :string
  end

  create_table "customerdetails", :force => true do |t|
    t.column "custid",       :string
    t.column "custname",     :string
    t.column "cardno",       :string
    t.column "customertype", :string
  end

  create_table "customertypes", :force => true do |t|
    t.column "ctypeid",       :string
    t.column "ctypedesc",     :string
    t.column "priority",      :integer
    t.column "thresholdtime", :time
  end

  create_table "customertypesbkp", :force => true do |t|
    t.column "ctypeid",        :string
    t.column "ctypedesc",      :string
    t.column "priority",       :integer
    t.column "thresholdtime",  :time
    t.column "downloadeddate", :date
  end

  create_table "displayscrollmsgs", :force => true do |t|
    t.column "scrollmsg", :string
    t.column "status",    :integer
  end

  create_table "displayscrollmsgsbkp", :force => true do |t|
    t.column "scrollmsg",      :string
    t.column "downloadeddate", :date
  end

  create_table "icicicard", :id => false, :force => true do |t|
    t.column "bin",        :string, :limit => 50
    t.column "product",    :string, :limit => 50
    t.column "expiredate", :string, :limit => 50
    t.column "priority",   :string, :limit => 5
  end

  create_table "nonstps", :force => true do |t|
    t.column "nonstpname", :string
    t.column "status",     :string, :limit => 1
    t.column "created_on", :date
    t.column "updated_on", :date
  end

  create_table "nonstpsbkp", :force => true do |t|
    t.column "nonstpname",     :string
    t.column "status",         :string, :limit => 1
    t.column "downloadeddate", :date
    t.column "created_on",     :date
    t.column "updated_on",     :date
  end

  create_table "pausedetails", :force => true do |t|
    t.column "counterno", :integer
    t.column "login",     :string
    t.column "pdate",     :date
    t.column "stime",     :time
    t.column "etime",     :time
    t.column "reason",    :string
    t.column "pflag",     :string,  :limit => 1
  end

  create_table "scrollmsgs", :force => true do |t|
    t.column "scrollmsg", :string
    t.column "status",    :integer, :default => 0
  end

  create_table "services", :force => true do |t|
    t.column "serviceid",     :string
    t.column "servicename",   :string
    t.column "thresholdtime", :time
    t.column "servicestatus", :string,  :limit => 1
    t.column "buttonno",      :integer
    t.column "priority",      :integer
    t.column "created_on",    :date
    t.column "updated_on",    :date
    t.column "serviceflag",   :integer, :limit => 5
    t.column "sid",           :string,  :limit => 50
    t.column "starttime",     :time
    t.column "endtime",       :time
  end

  create_table "servicesbkp", :force => true do |t|
    t.column "serviceid",      :string
    t.column "servicename",    :string
    t.column "thresholdtime",  :time
    t.column "servicestatus",  :string,  :limit => 1
    t.column "buttonno",       :integer
    t.column "priority",       :integer
    t.column "downloadeddate", :date
    t.column "created_on",     :date
    t.column "updated_on",     :date
    t.column "serviceflag",    :integer
    t.column "sid",            :string
    t.column "starttime",      :time
    t.column "endtime",        :time
  end

  create_table "settings", :force => true do |t|
    t.column "missingcount",      :integer
    t.column "missingtime",       :time
    t.column "returntime",        :string
    t.column "branchname",        :string
    t.column "paperstatus",       :string,  :default => "TRUE"
    t.column "purgingdata",       :integer
    t.column "accountscreentime", :string
  end

  create_table "statuses", :force => true do |t|
    t.column "branchname",         :string
    t.column "totaltokenserved",   :integer
    t.column "pendingtokencount",  :integer
    t.column "noofactivecounters", :integer
    t.column "goldcount",          :integer
    t.column "customercount",      :integer
    t.column "noncustomercount",   :integer
    t.column "printerstatus",      :string
    t.column "dqmstatus",          :string
  end

  create_table "stps", :force => true do |t|
    t.column "stpname",     :string
    t.column "servicetime", :time
    t.column "status",      :string, :limit => 1
    t.column "created_on",  :date
    t.column "serviceid",   :string
    t.column "updated_on",  :date
  end

  create_table "stpsbkp", :force => true do |t|
    t.column "stpname",        :string
    t.column "servicetime",    :time
    t.column "status",         :string, :limit => 1
    t.column "downloadeddate", :date
    t.column "created_on",     :date
    t.column "serviceid",      :string
    t.column "updated_on",     :date
  end

  create_table "tokendisplays", :force => true do |t|
    t.column "tokenno",   :string, :limit => 50
    t.column "counterno", :string, :limit => 50
  end

  create_table "tokenpendings", :force => true do |t|
    t.column "tokenno",       :string
    t.column "tokenid",       :integer
    t.column "ctypeid",       :string
    t.column "transdate",     :date
    t.column "generatedtime", :time
    t.column "serviceid",     :string
    t.column "counterno",     :integer
    t.column "tokenstatus",   :string,  :limit => 1
  end

  create_table "tokens", :force => true do |t|
    t.column "branchname",              :string
    t.column "totaltokenserved",        :integer
    t.column "pendingtokencount",       :integer
    t.column "Noofactivecounters",      :integer
    t.column "goldpendingcount",        :integer
    t.column "customerpendingcount",    :integer
    t.column "noncustomerpendingcount", :integer
    t.column "printerstatus",           :string
    t.column "dqmstatus",               :string
  end

  create_table "transactmaster", :force => true do |t|
    t.column "tokenno",       :string
    t.column "tokenid",       :integer
    t.column "ctypeid",       :string
    t.column "transdate",     :date
    t.column "generatedtime", :time
    t.column "serviceid",     :string
    t.column "counterno",     :integer
    t.column "accno",         :string
    t.column "login",         :string
    t.column "calledtime",    :time
    t.column "servicedtime",  :time
    t.column "timetaken",     :time
    t.column "waittime",      :time
    t.column "stpname",       :string
    t.column "nonstpname",    :string
    t.column "tokenstatus",   :string,  :limit => 1
    t.column "pauseflag",     :integer
    t.column "pausetime",     :time
    t.column "releasetime",   :time
    t.column "bulkcount",     :integer
    t.column "call1",         :time
    t.column "reasons",       :string
    t.column "missingflag",   :integer
    t.column "pullcounter",   :integer
    t.column "redirecttime",  :time
    t.column "exported",      :string,               :default => "FALSE"
  end

  create_table "transacts", :force => true do |t|
    t.column "tokenno",       :string
    t.column "tokenid",       :integer
    t.column "ctypeid",       :string
    t.column "transdate",     :date
    t.column "generatedtime", :time
    t.column "serviceid",     :string
    t.column "counterno",     :integer
    t.column "tokenstatus",   :string,  :limit => 1
    t.column "accno",         :string
    t.column "login",         :string
    t.column "calledtime",    :time,                  :default => '2000-01-01 00:00:00'
    t.column "servicedtime",  :time,                  :default => '2000-01-01 00:00:00'
    t.column "timetaken",     :time,                  :default => '2000-01-01 00:00:00'
    t.column "waittime",      :time,                  :default => '2000-01-01 00:00:00'
    t.column "stpname",       :string
    t.column "nonstpname",    :string
    t.column "pauseflag",     :integer
    t.column "pausetime",     :time
    t.column "releasetime",   :time,                  :default => '2000-01-01 00:00:00'
    t.column "bulkcount",     :integer
    t.column "call1",         :time,                  :default => '2000-01-01 00:00:00'
    t.column "reasons",       :string
    t.column "missingflag",   :integer
    t.column "pullcounter",   :integer
    t.column "redirecttime",  :time
    t.column "exported",      :string,                :default => "FALSE"
    t.column "accflag",       :string,  :limit => 50
  end

  create_table "users", :force => true do |t|
    t.column "login",       :string
    t.column "email",       :string
    t.column "password",    :string
    t.column "usertype",    :string
    t.column "userstatus",  :string,  :limit => 1
    t.column "loginstatus", :string,  :limit => 1, :default => "N"
    t.column "counterno",   :integer,              :default => 0
    t.column "firstname",   :string
    t.column "lastname",    :string
    t.column "created_on",  :date
    t.column "updated_on",  :date
  end

  create_table "usmappings", :force => true do |t|
    t.column "login",     :string
    t.column "serviceid", :string
  end

  create_table "versionhistories", :force => true do |t|
    t.column "javafd",      :string
    t.column "javatd",      :string
    t.column "rubyonrails", :string
  end

end
